### ISSUE TITLE
ERROR: trimmomatic is not installed.

### ISSUE THREAD

**Issue by leesaudan2** [viromelab/tracespipe#1]
I was following the [installation instructions](https://github.com/viromelab/tracespipe#21-installation).

When I run
```
./TRACESPipe.sh --install
```

I get this error:
```
Downloading and Extracting Packages
mummer4-4.0.0rc1     | 636 KB    | #################################### | 100% 
Preparing transaction: done           
Verifying transaction: done
Executing transaction: done
Checking trimmomatic ... ERROR: trimmomatic is not installed.
```

But trimmomatic has been installed in the conda environment:
```
$ conda list | grep trim
trimmomatic               0.39                 hdfd78af_2    bioconda
$ conda run trimmomatic -version
0.39
```

What's wrong?

I'm using version d685d0cf82db6da631a11e2c9c2338c847418d19.

**Comment by pratas** [comment]
Hi, 
what happens if you run:
**trimmomatic -version**

**Comment by leesaudan2** [comment]
```
$ trimmomatic -version
bash: trimmomatic: command not found
```

**Comment by pratas** [comment]
It seems that trimmomatic is not installed.
Lets find out why. Please, run this:

conda install -c bioconda trimmomatic --yes

(it will try to install trimmomatic)

**Comment by leesaudan2** [comment]
Then, how come:
```
$ conda list | grep trim
trimmomatic               0.39                 hdfd78af_2    bioconda
$ conda run trimmomatic -version
0.39
```
???

**Comment by leesaudan2** [comment]
And more:
```
$ conda install -c bioconda trimmomatic --yes
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

$ conda run trimmomatic -version
0.39
```
Not installed???

**Comment by leesaudan2** [comment]
After
```
conda install -c bioconda trimmomatic --yes
```
I still get the same error message when running
```
./TRACESPipe.sh --install
```
:frowning_face:

**Comment by pratas** [comment]
Sorry, it is installed, but it seems that you don't have full access to the machine.
Your conda seems to be installed through a virtual interpreter.
Which operating systems are you using? Is it a virtual one?

**Comment by pratas** [comment]
This is a conda issue not from TRACESPipe. 
Once fixed, after running

**./TRACESPipe.sh --install**

if you run 

**trimmomatic -version**

you have to get the same output, which is

**0.39**

TRACESPipe assumes that the binaries for each tool (under conda) are directly accessible.

**Comment by leesaudan2** [comment]
No.  I'm not using any virtual interpreter.

I installed conda by following [these instructions](https://github.com/viromelab/tracespipe#21-installation).  This is on Linux (Debian bullseye/sid) on a real machine (x86_64).

**Comment by leesaudan2** [comment]
What do you mean by "full access"?  Root privilege?  It can't be installed as a normal user?

**Comment by pratas** [comment]
It can. I've tried in a new machine and it works fine.
Not sure why it doesn't on yours...

**Comment by pratas** [comment]
Can you generate a virtual linux (ubuntu) and test again?

**Comment by pratas** [comment]
Maybe the OS runs through the interpreter and does not add the binaries directly

**Comment by pratas** [comment]
For example if I do

locate trimmomatic

I get

/home/(user)/miniconda3/share/trimmomatic

or 

home/(user)/miniconda3/bin/trimmomatic

**Comment by pratas** [comment]
Please check you .bashrc

a see if there is something like:

`__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/(user)/miniconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/(user)/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/(user)/miniconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/(user)/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup`

**Comment by leesaudan2** [comment]
Yes, my .bashrc contains something similar.  However, it only adds ".../miniconda3/condabin" to my $PATH.  It doesn't add ".../miniconda3/bin" to my $PATH.

Adding ".../miniconda3/bin" *manually* to $PATH makes it work.  I'm still puzzled why those lines added to .bashrc by `conda init` do not add that to $PATH.  It should be a conda problem, then.

Thanks.

**Comment by 1999whx** [comment]
I have the same problem，but I still don't know how to issue it ,so I want to konw the solution,please.
