### ISSUE TITLE
ERROR: ivar is not installed

### ISSUE THREAD

**Issue by iek** [viromelab/tracespipe#2]
Hello, despite running `conda install ivar` to install ivar, when I run the command `./TRACESPipe.sh --install`, I get the following error:

`Checking trimmomatic ... SUCCESS!
Checking cryfa ... SUCCESS!
Checking MAGNET ... SUCCESS!
Checking FALCON ... SUCCESS!
Checking gto ... SUCCESS!
Checking spades.py ... SUCCESS!
Checking igv ... SUCCESS!
Checking bowtie2 ... SUCCESS!
Checking samtools ... SUCCESS!
Checking bcftools ... SUCCESS!
Checking bedops ... SUCCESS!
Checking bedtools ... SUCCESS!
Checking fastq_pair ... SUCCESS!
Checking efetch ... SUCCESS!
Checking mapDamage ... SUCCESS!
Checking tabix ... SUCCESS!
Checking AdapterRemoval ... SUCCESS!
Checking bwa ... SUCCESS!
Checking art_illumina ... SUCCESS!
Checking blastn ... SUCCESS!
Checking dnadiff ... SUCCESS!
Checking ivar ... ERROR: ivar is not installed.`

Do you have suggestions on how to navigate this error? Thank you so much!

**Comment by pratas** [comment]
Hi,

yes, ivar is only for a development version.
Code has been adapted.
Please reclone tracespipe and follow the normal procedure.

Best reagrds
